- name: creating md5 hash for replication password
  shell: echo "md5$(echo -n '{{ postgresql_conf.replication_pass }}{{ postgresql_conf.replication_user }}' | md5sum | awk '{print $1}')"
  register: encrypted_pass

- name: manage postgresql replication user
  postgresql_user:
    name: '{{ postgresql_conf.replication_user }}'
    password: '{{ encrypted_pass.stdout }}'
    role_attr_flags: LOGIN,REPLICATION
    expires: infinity
    encrypted: yes
  become: yes
  become_method: su
  become_user: '{{ postgresql.user }}'

- name: manage replication in pg_hba
  blockinfile:
    dest: '{{ postgresql_conf.datadir }}/pg_hba.conf'
    block: |
      host    all             all             0.0.0.0/0                md5
      host    replication     {{ postgresql_conf.replication_user }}      0.0.0.0/0                md5
  notify: restart postgresql
