- name: install postgresql repo
  yum:
    name: '{{ postgresql.repo_url }}'
    state: present

- name: install epel
  yum:
    name: epel-release
    state: latest

- name: install packages
  yum:
    name: '{{ postgresql.packages }}'
    state: latest
