- name: upgrade pip
  pip:
    name: pip
    state: latest
  ignore_errors: yes

- name: install pexpect
  pip:
    name: pexpect
    state: latest
  ignore_errors: yes

- name: remove postgresql data directory for slaves
  shell: 'rm -rf {{ postgresql_conf.datadir }}'
  args:
    creates: '{{ postgresql_conf.datadir }}/recovery.conf'
    warn: False
  become: yes
  become_method: su
  become_user: '{{ postgresql.user }}'

- name: reinit postgresql slave directory
  expect:
    command: 'pg_basebackup -h {{ postgresql_conf.masterip }} -D {{ postgresql_conf.datadir }} -R -P -U replication --wal-method=stream'
    responses:
      Password:
        - '{{ postgresql_conf.replication_pass }}'
    creates: '{{ postgresql_conf.datadir }}/base'
  become: yes
  become_method: su
  become_user: '{{ postgresql.user }}'

- name: manage posgtresql conf
  template:
    src: templates/postgresql.conf
    dest: '{{ postgresql_conf.datadir }}/postgresql.conf'
    owner: '{{ postgresql.user }}'
    group: '{{ postgresql.user }}'
    mode: 0644
  notify: restart postgresql
